name: lens
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - pip
  - pytorch
  - torchvision
  - tensorboard
  - pyyaml
  - pip:
    - SimpleITK
    - ipywidgets
    - sacred
    - nbdev
    - fastnumbers
    - natsort
  - ipykernel
  - tqdm
  - matplotlib
  - scikit-learn
  - pandas
  - numpy
  - opencv
  - seaborn
  - imgaug
  - albumentations
  